# Generated by Django 5.1.3 on 2024-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_dishes_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
