# Generated by Django 5.1.3 on 2024-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_dishes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
